### PR TITLE
Format and typo fixes in README.md

### PR DESCRIPTION
**Pull request by xexyl**
The file favicon.ico was added (a copy of the IOCCC website favicon.ico) so that a 404 is not generated when opening the page.

The file ioccc-submit-index-page.jpg was added to show what the web page should look like.

The .gitignore has .DS_Store added to it.

Moved indented commands in command blocks to first column as that is an IOCCC website thing for later use and GitHub should now show the text in the first column to make it slightly easier to see longer lines.

Clarified and typo checked (up to at least the part where I can check; I could not check all because docker is deprecated and part of the documentation only works if docker is running - as I have not put it on my web server due to that being a production server).

There might have been some other changes in README.md but until the docker in documentation has been corrected (to refer to how it should be done now that docker is deprecated) I cannot easily verify that things are good.

### CODE REVIEW

**Comment by xexyl** [comment]
Once you have corrected the docker part I'll proceed. Do you wish me to check other files too ? Let me know and I'll do so!

I have to go afk now but will check the guidelines/rules in the other repo in a while.

**Review by lcn2 — APPROVED** [review]
Very nice update to `READMD.md` @xexyl, thank you.

FYI: The critical location for the `favicon.ico` file is on the actual web site.  Currently [submit.ioccc.org](https://submit.ioccc.org) only has a test page (https://submit.ioccc.org/index.html), a `favicon.ico` file, and a `robots.txt` file.  Nevertheless we will keep that file here for testing purposes.

BTW: We are hoping to get this code running on the [submit.ioccc.org](https://submit.ioccc.org) today (2024 Dec 07) or by tomorrow (2024 Dec 08) when we have another session with @elear, the original author of this code.

We are pleased to see that you were able to run the code enough to grab a screenshot.  Congratulations :-).

We recommend that, under your test it further by creating a random user.  Please consider doing this:

```sh
bin/ioccc_passwd.py -U -c
```

This will output both a UUID username and initial password.  This is going to be the primary action that the IOCCC judges will cause to happen when someone registers for the IOCCC (by joining the announcement only mailing list).   You should then be able to login with that new UUID username and initial password, and then because you also used `-c`, you will be asked to select a new password.

Once you have changed your password, please use the `mkiocccentry(1)` from the "other repo" to generate files for your UUID and try to upload them.

Once you have done that (and you MUST have previously logged in to do this, thus setting up the slot directory tree under `users/username/`), try changing a slot comment such as:

```sh
bin/set_slot_status.py UUID-USER-NAME 0 'the format of this submission has been validated'
```

This will simulate what will happen when an IOCCC judge fetched the submission file, runs `txzchk(1)` on it, and then untars it, and then runs `chkentry(1)` on it, and then "informs" the submitter that all is well, format wise.

# REQUEST

Please consider running thru the above steps **AND CAPTURE IMAGES** and then consider updating the **FAQ** on the "other other repo :-)" as this **WILL** help complete the next two gating items for the **Great Fork Merge**.

Doing the above is the **HIGHEST PRIORITY** and would be much appreciated.

2nd in priority would be to improve the wording / fix typos for any of the generated web pages.

**THANK YOU**, @xexyl, for your help!

**Comment by lcn2** [comment]
p.s. with 50ffb627510262f2b88adf2dd27c678a4db66647 we moved ioccc-submit-index-page.jpg under static/moved ioccc-submit-index-page.jpg under static

**Comment by xexyl** [comment]
> Very nice update to `READMD.md` @xexyl, thank you.
> 
> FYI: The critical location for the `favicon.ico` file is on the actual web site. Currently [submit.ioccc.org](https://submit.ioccc.org) only has a test page (https://submit.ioccc.org/index.html), a `favicon.ico` file, and a `robots.txt` file. Nevertheless we will keep that file here for testing purposes.
> 
> BTW: We are hoping to get this code running on the [submit.ioccc.org](https://submit.ioccc.org) today (2024 Dec 07) or by tomorrow (2024 Dec 08) when we have another session with @elear, the original author of this code.
> 
> We are pleased to see that you were able to run the code enough to grab a screenshot. Congratulations :-).
> 
> We recommend that, under your test it further by creating a random user. Please consider doing this:
> 
> ```shell
> bin/ioccc_passwd.py -U -c
> ```
> 
> This will output both a UUID username and initial password. This is going to be the primary action that the IOCCC judges will cause to happen when someone registers for the IOCCC (by joining the announcement only mailing list). You should then be able to login with that new UUID username and initial password, and then because you also used `-c`, you will be asked to select a new password.
> 
> Once you have changed your password, please use the `mkiocccentry(1)` from the "other repo" to generate files for your UUID and try to upload them.
> 
> Once you have done that (and you MUST have previously logged in to do this, thus setting up the slot directory tree under `users/username/`), try changing a slot comment such as:
> 
> ```shell
> bin/set_slot_status.py UUID-USER-NAME 0 'the format of this submission has been validated'
> ```
> 
> This will simulate what will happen when an IOCCC judge fetched the submission file, runs `txzchk(1)` on it, and then untars it, and then runs `chkentry(1)` on it, and then "informs" the submitter that all is well, format wise.
> 
> Please consider running thru the above steps **AND CAPTURE IMAGES** and then consider updating the **FAQ** on the "other other repo :-)" as this **WILL** help complete the next two gating items for the **Great Fork Merge&**.
> 
> Doing the above is the **HIGHEST PRIORITY** and would be much appreciated.
> 
> 2nd in priority would be to improve the wording / fix typos for any of the generated web pages.
> 
> **THANK YOU**, @xexyl, for your help!

You are most welcome!

As for the running of the commands beyond what I looked at. The reason I stopped is because it was still talking about docker. I can try setting this up on the server in the private vhost and it should be okay as long as I can get the appropriate tools. The real trouble is I'll have to bind to another address as obviously there is no GUI on the server.

I'll try looking into this soon as you want to get the submit server up today if you can (I really hope so!).

But I don't know. Should I wait until you fix the docker reference? I don't know. I'll hold off for a bit of time but then if I don't hear anything back I'll see if I can get it working. I should be available for at least a few more hours.

**Comment by lcn2** [comment]
> > Very nice update to `READMD.md` @xexyl, thank you.
> > FYI: The critical location for the `favicon.ico` file is on the actual web site. Currently [submit.ioccc.org](https://submit.ioccc.org) only has a test page (https://submit.ioccc.org/index.html), a `favicon.ico` file, and a `robots.txt` file. Nevertheless we will keep that file here for testing purposes.
> > BTW: We are hoping to get this code running on the [submit.ioccc.org](https://submit.ioccc.org) today (2024 Dec 07) or by tomorrow (2024 Dec 08) when we have another session with @elear, the original author of this code.
> > We are pleased to see that you were able to run the code enough to grab a screenshot. Congratulations :-).
> > We recommend that, under your test it further by creating a random user. Please consider doing this:
> > ```shell
> > bin/ioccc_passwd.py -U -c
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will output both a UUID username and initial password. This is going to be the primary action that the IOCCC judges will cause to happen when someone registers for the IOCCC (by joining the announcement only mailing list). You should then be able to login with that new UUID username and initial password, and then because you also used `-c`, you will be asked to select a new password.
> > Once you have changed your password, please use the `mkiocccentry(1)` from the "other repo" to generate files for your UUID and try to upload them.
> > Once you have done that (and you MUST have previously logged in to do this, thus setting up the slot directory tree under `users/username/`), try changing a slot comment such as:
> > ```shell
> > bin/set_slot_status.py UUID-USER-NAME 0 'the format of this submission has been validated'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will simulate what will happen when an IOCCC judge fetched the submission file, runs `txzchk(1)` on it, and then untars it, and then runs `chkentry(1)` on it, and then "informs" the submitter that all is well, format wise.
> > Please consider running thru the above steps **AND CAPTURE IMAGES** and then consider updating the **FAQ** on the "other other repo :-)" as this **WILL** help complete the next two gating items for the **Great Fork Merge&**.
> > Doing the above is the **HIGHEST PRIORITY** and would be much appreciated.
> > 2nd in priority would be to improve the wording / fix typos for any of the generated web pages.
> > **THANK YOU**, @xexyl, for your help!
> 
> You are most welcome!
> 
> As for the running of the commands beyond what I looked at. The reason I stopped is because it was still talking about docker. I can try setting this up on the server in the private vhost and it should be okay as long as I can get the appropriate tools. The real trouble is I'll have to bind to another address as obviously there is no GUI on the server.
> 
> I'll try looking into this soon as you want to get the submit server up today if you can (I really hope so!).
> 
> But I don't know. Should I wait until you fix the docker reference? I don't know. I'll hold off for a bit of time but then if I don't hear anything back I'll see if I can get it working. I should be available for at least a few more hours.

With commit d67c3337e6d48be25e1aeb92d683f8542d39c4ad, old references to docker have been removed from `README.md` except for the deprecated section near the bottom.

**Comment by xexyl** [comment]
Oh .. I see now the problem I had, maybe! I am missing the file lock module. I'll see about fixing that in a little bit and see if that helps.

**Comment by xexyl** [comment]
Actually .. how do i get that module? I see:

```
Traceback (most recent call last):
  File "/Users/cody/code/xexyl-submit-tool/./bin/ioccc_passwd.py", line 24, in <module>
    from ioccc_common import *
  File "/Users/cody/code/xexyl-submit-tool/bin/ioccc_common.py", line 51, in <module>
    from filelock import Timeout, FileLock
ModuleNotFoundError: No module named 'filelock'
```

but no reference to it in README.md.

**Comment by xexyl** [comment]
Might have done it .. checking.

**Comment by lcn2** [comment]
> Actually .. how do i get that module? I see:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/cody/code/xexyl-submit-tool/./bin/ioccc_passwd.py", line 24, in <module>
>     from ioccc_common import *
>   File "/Users/cody/code/xexyl-submit-tool/bin/ioccc_common.py", line 51, in <module>
>     from filelock import Timeout, FileLock
> ModuleNotFoundError: No module named 'filelock'
> ```
> 
> but no reference to it in README.md.

Do you member to do:

```sh
rm -rf venv __pycache__ && python3 -m venv venv
. ./venv/bin/activate
pip install --upgrade pip
python3 -m pip install -r ./etc/requirements.txt
```

Python does not "_play well with others_" and you can only run them under those conditions.

**Comment by xexyl** [comment]
I got it actually. Let me see if having installed that module works now.

**Comment by lcn2** [comment]
> I got it actually. Let me see if having installed that module works now.

How did you install it?

Did you remember to:

```sh
rm -rf venv __pycache__ && python3 -m venv venv
. ./venv/bin/activate
pip install --upgrade pip
python3 -m pip install -r ./etc/requirements.txt
```

That seems to be required to run any commands.

**Comment by xexyl** [comment]
I did this time .. but I think I might have to put the server in the background. Trying that. I'll start over with what you have just to be sure.

**Comment by xexyl** [comment]
Oh it doesn't want to stay working in the background.

So the question is which commands do I need to run in another tab so that the commands will work?

**Comment by lcn2** [comment]
doing a commit ... just a second ...

**Comment by xexyl** [comment]
Sure.

**Comment by lcn2** [comment]
With commit 8f5f1202f0cd40ebbd9d6bf30d8d926d4ca2a8ae we have reminded uses to setup their python environment as "_python does not play well with others_".

**Comment by xexyl** [comment]
Pulled it already but I have to determine which steps I am missing. I guess I might have to run some of the commands in another tab so I can run the commands in that tab (like the passwd util as obviously I can't do that when the server is running in that tab).

**Comment by xexyl** [comment]
Okay that was it! Got a user now ... will continue.

**Comment by lcn2** [comment]
Committing an edit to `README.md` very soon ...

**Comment by lcn2** [comment]
With commit 82b0885cabd838d133a5a9c0eed0188c626cb5d3 we have tried to remind the other that they must **setup python the environment** before running commands in test mode.

Feel free to improve how this is worked / done in `README.md`, @xexyl.

**Comment by xexyl** [comment]
Well this is unfortunate. Check this:

```
Enter IOCCC contest ID or test: 5ea3b0c8-61f1-42e7-9b9f-89a6ade01b17
IOCCC contest IDs are in the form:

    xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx

where 'x' is a hex character, 4 is the UUID version and the variant 1.

Enter IOCCC contest ID or test: 
```

?

**Comment by xexyl** [comment]
Okay so either a bug in the server or something funny with mkiocccentry. This is what happens. I changed the debug level to 0:

```
debug[0]: invalid: UUID variant hex char != UUID_VARIANT: a
debug[0]: invalid: UUID variant hex char: 9 is not UUID_VARIANT: a
```

**Comment by xexyl** [comment]
I do have screenshots though .. of the steps to this point. I can't test it further obviously unless I am to modify my copy of mkiocccentry to allow it temporarily.

**Comment by lcn2** [comment]
looking at the UUID issue ...

**Comment by xexyl** [comment]
Thanks!

**Comment by lcn2** [comment]
This generates the proper UUID type:

```sh
python3 -m uuid -u uuid4
```

... looking more ...

**Comment by xexyl** [comment]
Okay thanks.

**Comment by lcn2** [comment]
Perhaps the `mkiocccentry(1)` code check on UUID strings is incorrect?   It might be the 

Perhaps the _xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx_ is incorrect and that it should be just `xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx` (not insisting on the "a")?

We could hack the code in this repo to force the "a" in the UUID as well.  This might be the better choice.

Suggestions, @xexyl ?

**Comment by xexyl** [comment]
> Perhaps the `mkiocccentry(1)` code check on UUID strings is incorrect? Perhaps the _xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx_ is incorrect and that it should be just `xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx` (not insisting on the "a")?
> 
> We could hack the code in this repo to force the "a" in the UUID as well. This might be the better choice.
> 
> Suggestions, @xexyl ?

It might be the quicker way for this IOCCC? Then after IOCCC28 we can change the way the check is enforced?

**Comment by xexyl** [comment]
> Perhaps the `mkiocccentry(1)` code check on UUID strings is incorrect? Perhaps the _xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx_ is incorrect and that it should be just `xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx` (not insisting on the "a")?
> 
> We could hack the code in this repo to force the "a" in the UUID as well. This might be the better choice.
> 
> Suggestions, @xexyl ?
> 
> ## UPDATE 0
> It would be a simple hack to `bin/ioccc_passwd.py` to force the "a" into the UUID that is generated under the `-U` condition.

For now I think that's a better idea .. but I do think the check in mkiocccentry should, if it's not correct, be fixed in time.

**Comment by lcn2** [comment]
Fixing `bin/ioccc_passwd.py` now ...

BTW: @xexyl, this was a **VERY GOOD** catch.   There is a random chance that `str(uuid.uuid4())` returns "a".  We guess that when we tested it, it just happened to return an "a".   Heh 😏

**Comment by xexyl** [comment]
> Fixing `bin/ioccc_passwd.py` now ...
> 
> BTW: @xexyl, this was a **VERY GOOD** catch. There is a random chance that `str(uuid.uuid4())` returns "a". We guess that when we tested it, it just happened to return an "a". Heh 😏

That's true. Lucky catch indeed! Glad I did it when I did for that reason.

**Comment by lcn2** [comment]
FYI:  Modifying `bin/ioccc_passwd.py` to include this code:

```py
# The IOCCC mkiocccentry(1) tool, version: 1.0.8 2024-08-23,
# requires the UUID based username to be of this form:
#
#   xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx
#
# While str(uuid.uuid4()) does generate a '4' in the
# 14th character postion, the 19th position seems
# to be able to be any of [89ab].  We force the 19th
# character position to be an 'a' for now.
#
tmp = list(username)
# paranoia
tmp[14] = '4'
# mkiocccentry(1) tool, version: 1.0.8 2024-08-23 workaround
tmp[19] = 'a'
username = ''.join(tmp)
```

See commit 81f598226254a91c418176be06168eacccd36ebe/

**Comment by xexyl** [comment]
Will try it out .. have to take care of some reminders first (but that'll only take a minute or two). I need to do one other thing too and then I'll start the process over, making sure to take new screenshots (after deleting the old ones).

**Comment by lcn2** [comment]
p.s. Please also review `README.md` as our edits to try and fix the python environment issue was dine very quickly and may be able to be improved.

**Comment by xexyl** [comment]
> p.s. Please also review `README.md` as our edits to try and fix the python environment issue was dine very quickly and may be able to be improved.

I guess it's more important that I get the submit procedure tested though, right?

**Comment by xexyl** [comment]
Okay deleted screenshots .. will try again after pulling.

**Comment by lcn2** [comment]
We created [issue 1035 in the mkicccentry repo](https://github.com/ioccc-src/mkiocccentry/issues/1035) as a **POST-IOCCC28** issue in order to remember undo the work-a-round when `mkiocccentry(1)` is corrected.

**Comment by xexyl** [comment]
Another problem when trying this ...

```
Message(s):

Filename for slot 0 must match this regular expression: ^submit\.5ea3b0c8-61f1-42e7-9b9f-89a6ade01b17-0\.[1-9][0-9]{9,}\.txz$
```

The filename was:

```
submit.6668e3a9-dfe6-4f90-a09e-35694b4a7187-0.1733601912.txz
```

and of course was generated by mkiocccentry.

**Comment by xexyl** [comment]
I will possibly be leaving soonish but I'm happy to add these to the FAQ tomorrow if I can't get it in today.

**Comment by lcn2** [comment]
> Another problem when trying this ...
> 
> ```
> Message(s):
> 
> Filename for slot 0 must match this regular expression: ^submit\.5ea3b0c8-61f1-42e7-9b9f-89a6ade01b17-0\.[1-9][0-9]{9,}\.txz$
> ```
> 
> The filename was:
> 
> ```
> submit.6668e3a9-dfe6-4f90-a09e-35694b4a7187-0.1733601912.txz
> ```
> 
> and of course was generated by mkiocccentry.

It seems that you were still logged in as user "5ea3b0c8-61f1-42e7-9b9f-89a6ade01b17" so the rejection the file `submit.6668e3a9-dfe6-4f90-a09e-35694b4a7187-0.1733601912.txz` was correct.

There is a **((Logout))** button that you need to use.  :-)

**Comment by xexyl** [comment]
Strange because I actually opened it anew and then logged in with new password and changed it. I'll try again though.

**Comment by lcn2** [comment]
> Strange because I actually opened it anew and then logged in with new password and changed it. I'll try again though.

The flaks login keeps track of your current username, so if you want to test another username you must logout and login to that new user.

**Comment by xexyl** [comment]
> > Strange because I actually opened it anew and then logged in with new password and changed it. I'll try again though.
> 
> The python `flask-login` module keeps track of your current username, so if you want to test another username you must logout and login to that new user.

I'm this time also deactivating first and then doing everything over again. Hopefully that'll sort it out.

**Comment by xexyl** [comment]
Okay I forgot. Have to recreate the tarball .. was about to report another problem. Hold please. Hopefully this works.

**Comment by lcn2** [comment]
OK .. will be back in a few minutes to see what you might have found.

**Comment by xexyl** [comment]
Works fine .. have to go afk a moment too.

**Comment by xexyl** [comment]
Got screenshots. Now will try the other steps you asked and get screenshots if necessary. After that I can add them to the FAQ.

**Comment by xexyl** [comment]
> > > Very nice update to `READMD.md` @xexyl, thank you.
> > > FYI: The critical location for the `favicon.ico` file is on the actual web site. Currently [submit.ioccc.org](https://submit.ioccc.org) only has a test page (https://submit.ioccc.org/index.html), a `favicon.ico` file, and a `robots.txt` file. Nevertheless we will keep that file here for testing purposes.
> > > BTW: We are hoping to get this code running on the [submit.ioccc.org](https://submit.ioccc.org) today (2024 Dec 07) or by tomorrow (2024 Dec 08) when we have another session with @elear, the original author of this code.
> > > We are pleased to see that you were able to run the code enough to grab a screenshot. Congratulations :-).
> > > We recommend that, under your test it further by creating a random user. Please consider doing this:
> > > ```shell
> > > bin/ioccc_passwd.py -U -c
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will output both a UUID username and initial password. This is going to be the primary action that the IOCCC judges will cause to happen when someone registers for the IOCCC (by joining the announcement only mailing list). You should then be able to login with that new UUID username and initial password, and then because you also used `-c`, you will be asked to select a new password.
> > > Once you have changed your password, please use the `mkiocccentry(1)` from the "other repo" to generate files for your UUID and try to upload them.
> > > Once you have done that (and you MUST have previously logged in to do this, thus setting up the slot directory tree under `users/username/`), try changing a slot comment such as:
> > > ```shell
> > > bin/set_slot_status.py UUID-USER-NAME 0 'the format of this submission has been validated'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will simulate what will happen when an IOCCC judge fetched the submission file, runs `txzchk(1)` on it, and then untars it, and then runs `chkentry(1)` on it, and then "informs" the submitter that all is well, format wise.
> > > Please consider running thru the above steps **AND CAPTURE IMAGES** and then consider updating the **FAQ** on the "other other repo :-)" as this **WILL** help complete the next two gating items for the **Great Fork Merge&**.
> > > Doing the above is the **HIGHEST PRIORITY** and would be much appreciated.
> > > 2nd in priority would be to improve the wording / fix typos for any of the generated web pages.
> > > **THANK YOU**, @xexyl, for your help!
> > 
> > 
> > You are most welcome!
> > As for the running of the commands beyond what I looked at. The reason I stopped is because it was still talking about docker. I can try setting this up on the server in the private vhost and it should be okay as long as I can get the appropriate tools. The real trouble is I'll have to bind to another address as obviously there is no GUI on the server.
> > I'll try looking into this soon as you want to get the submit server up today if you can (I really hope so!).
> > But I don't know. Should I wait until you fix the docker reference? I don't know. I'll hold off for a bit of time but then if I don't hear anything back I'll see if I can get it working. I should be available for at least a few more hours.
> 
> With commit [d67c333](https://github.com/ioccc-src/submit-tool/commit/d67c3337e6d48be25e1aeb92d683f8542d39c4ad), old references to docker have been removed from `README.md` except for the deprecated section near the bottom.
> 
> ## UPDATE 0
> While we are working to get the code running under apache on the server, it would be **VERY HELPFUL** if you could obtain the needed screenshots by running the code and updating the FAQ in the "other repo? accordingly.
> 

Doing that now.

> We recommend that you put such images under `static/` in terms of this repo, and try not to have those images start with the letters _ioccc_, @xexyl.

That means in this repo, right?

> 
> You might also wish to either save those images at 50% size, or when you reference them use 1/2 their pixel width and 1/2 their pixel height in the markdown so that the image ration looks normal.

Probably the latter .. that goes for the other repo but what about this one too?

**Comment by lcn2** [comment]
> > We recommend that you put such images under `static/` in terms of this repo, and try not to have those images start with the letters _ioccc_, @xexyl.
> 
> That means in this repo, right?

Correct.

> > You might also wish to either save those images at 50% size, or when you reference them use 1/2 their pixel width and 1/2 their pixel height in the markdown so that the image ration looks normal.
> 
> Probably the latter .. that goes for the other repo but what about this one too?

Yes.

**Comment by lcn2** [comment]
This is **very helpful**, @xexyl and **very much appreciated**, @xexyl .. need to fining "getting up" .. will return in a few minutes.

**Comment by xexyl** [comment]
> This is **very helpful**, @xexyl and **very much appreciated**, @xexyl .. need to fining "getting up" .. will return in a few minutes.

Best wishes! Been awake since 0330 this morning .. which is a bit too early for me, though it's certainly been far worse. I'll be having my dinner soon but I'll be awake for many more hours yet.

I'm not seeing the upd

**Comment by xexyl** [comment]
Okay I got the updated message ... had to log out (as I guessed) and back in. All good. I'll try getting the FAQ sorted now.

**Comment by xexyl** [comment]
> > > We recommend that you put such images under `static/` in terms of this repo, and try not to have those images start with the letters _ioccc_, @xexyl.
> > 
> > 
> > That means in this repo, right?
> 
> Correct.
> 
> > > You might also wish to either save those images at 50% size, or when you reference them use 1/2 their pixel width and 1/2 their pixel height in the markdown so that the image ration looks normal.
> > 
> > 
> > Probably the latter .. that goes for the other repo but what about this one too?
> 
> Yes.
> 
> ## UPDATE 0
> We noticed that the after commit [74c387b](https://github.com/ioccc-src/submit-tool/commit/74c387b85a5502818c60b80568405e280571f2a9) the included image looked a bit odd. It turned out that the pixel height and pixel width were not proportional with the image size. So we looked at the true image size and adjusted the HTML to use the true pixel height and pixel width, but that looked too large, so we reduced the HTML pixel height and pixel width by 50% and it looked better.

Yeah that's my fault .. just yank pasted from the markdown guidelines. I did not expect that to be much of a problem but I also did not think about it. Thanks for fixing.


> 
> We don't think we need full size images for the FAQ and this `README.md` file.

Please define 'full size' images. Do you mean it should be scaled down? I guess that's what you mean, based on the other comments (and this one), but I want to be sure.

**Comment by lcn2** [comment]
> > We don't think we need full size images for the FAQ and this `README.md` file.
> 
> Please define 'full size' images. Do you mean it should be scaled down? I guess that's what you mean, based on the other comments (and this one), but I want to be sure.

The file `static/login-example.jpg` is _1324x1316_"

```sh
$ file static/login-example.jpg
static/login-example.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 144x144, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=4, xresolution=62, yresolution=70, resolutionunit=2], baseline, precision 8, 1324x1316, components 3
```

So "_full size_" would be a "``". 

We hacked the HTML to use a 50% size: ``".

We could;d have use a tool to scale down the `static/login-example.jpg` as well if we wanted to do so, but that is not critical to do so.

**Comment by xexyl** [comment]
> > > We don't think we need full size images for the FAQ and this `README.md` file.
> > 
> > 
> > Please define 'full size' images. Do you mean it should be scaled down? I guess that's what you mean, based on the other comments (and this one), but I want to be sure.
> 
> The file `static/login-example.jpg` is _1324x1316_:
> 
> ```shell
> $ file static/login-example.jpg
> static/login-example.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 144x144, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=4, xresolution=62, yresolution=70, resolutionunit=2], baseline, precision 8, 1324x1316, components 3
> ```
> 
> So "_full size_" would be a "``".
> 
> We hacked the HTML to use a 50% size: ``".
> 
> We could;d have use a tool to scale down the `static/login-example.jpg` as well if we wanted to do so, but that is not critical to do so.

Right .. you do mean that. Sure you can use ImageMagick. The way you did it is easier. When I've updated the FAQ you might or might not want to adjust the images by which I mean maybe you will feel some of it can be cropped. I'll let you decide on that though.

**Comment by xexyl** [comment]
> > > We don't think we need full size images for the FAQ and this `README.md` file.
> > 
> > 
> > Please define 'full size' images. Do you mean it should be scaled down? I guess that's what you mean, based on the other comments (and this one), but I want to be sure.
> 
> The file `static/login-example.jpg` is _1324x1316_:
> 
> ```shell
> $ file static/login-example.jpg
> static/login-example.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 144x144, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=4, xresolution=62, yresolution=70, resolutionunit=2], baseline, precision 8, 1324x1316, components 3
> ```
> 
> So "_full size_" would be a "``".
> 
> We hacked the HTML to use a 50% size: ``".
> 
> We could have use a tool to scale down the `static/login-example.jpg` as well if we wanted to do so, but that is not critical to do so.
> 
> ## UPDATE 0
> Now off to brush teeth, shave, shower .. be back in a few minutes.

Enjoy (the shower :-) ).

**Comment by xexyl** [comment]
Looking at this more .. I did add a meta for UTF-8 in the html files and I also fixed a typo in one of the html files. I have other things to consider too including a script that will reset the state to test the submit server, though that might not be needed except in the development phase.

**Pull request merged**
