### PR TITLE
Typo fixes/clarifications in README.md

### PR DESCRIPTION
**Pull request by xexyl**
This removes some amusing ambiguity that was probably not intended (though a part of me  hopes it was even if it should be removed).

Fun word for people who do not know: amphibology: a phrase or sentence that is grammatically ambiguous (see also amphibolous).

### CODE REVIEW

**Comment by lcn2** [comment]
We won't be able to consider any PRs against this repo as it is under very active development and because sincerity appears to be one of the leading qualities of the Internet 🛜 service we are using: uploading any changes to this repo may 1-2 weeks again. 

We may end up manually merging the target lines of this PR, assuming those lines have not already changed and then rejecting this PR.  That is TBD.

**Comment by xexyl** [comment]
No problem at all! I totally understand. Hope the development is going well.

**Comment by lcn2** [comment]
Thank you, @xexyl, for these edits.   We have added the changes made in this PR manually.  We have updated some major changes to to repo, and as such this PR no longer applies.

You may wish to update your clone of this repo.

Given the above we will close with comment.

Further comments, edits, and corrections based on the new master are welcome.

**Comment by xexyl** [comment]
> Thank you, @xexyl, for these edits. We have added the changes made in this PR manually. We have updated some major changes to to repo, and as such this PR no longer applies.
> 

I understand. Glad it was helpful though (late though this is):

<hr>
Need brooks no delay, yet late is better than never.
<hr>

.. even though that's a nonsense thing he says :-)


> You may wish to update your clone of this repo.
> 

Of course .. always do. Thanks for the reminder though!

> Given the above we will close with comment.
> 
> Further comments, edits, and corrections based on the new master are welcome.

Well I know it's late and after I already have done this but .. I'm glad I could help with this too.

**Comment by lcn2** [comment]
Hello 👋🏻 @xexyl,

Something went wrong with this PR it was closed but not committed. Not sure why. 

We have made edits to the README.md in the mean time. 

Perhaps you could try and re-apply your edits?

**Comment by xexyl** [comment]
> This repo is being re-organized in order to turn the main part of the code into a python package.  Thus, stuff will move around there will be a change the way people build and test this code. 
> 
> This is all being done in effort to be able to run this code under a web server.

Ahh so the comment you referenced in the other repo is this one. 

Okay so: I guess that it would be good if I waited here before I were to make more updates to the documentation etc.?

Of course if you want testing under a web server I will have to configure a python module for apache but I can do that on the private vhosts. 

Let me know what I can do and I will be happy to help where I can!

**Pull request closed without merging**
